#!/bin/sh

exec /opt/consul/consul-template/consul-template \
  -consul 172.17.1.226:8500 \
  -template "/tmp/haproxy.ctmpl:/etc/haproxy/haproxy.cfg:/usr/sbin/haproxy reload -db -f /etc/haproxy/haproxy.cfg || true"
